### PR TITLE
Resolves Issue #72

### LINKED ISSUE #72: No way to print event cookie
There is no way to output the event cookie, this can be useful when processing output for events like move_from and move_to.

This patch applies cleanly to 3.14 and adds a %c format specifier for the event cookie in hex:
```
--- libinotifytools/src/inotifytools.c.orig     2014-10-23 18:05:24.000000000 +0100
+++ libinotifytools/src/inotifytools.c  2014-10-23 18:15:47.000000000 +0100
@@ -1881,6 +1881,12 @@
                        continue;
                }

+               if ( ch1 == 'c' ) {
+                       ind += snprintf( &out[ind], size-ind, "%x", event->cookie);
+                       ++i;
+                       continue;
+               }
+
                if ( ch1 == 'e' ) {
                        eventstr = inotifytools_event_to_str( event->mask );
                        strncpy( &out[ind], eventstr, size - ind );
```

### PR DESCRIPTION
**Pull request by tcf909**
Makes unique id (cookie) available using "%c" as a formatting option.

Original code by mrspuratic

### CODE REVIEW

**Comment by ericcurtin** [comment]
Thanks very much for the contribution! There's a two test frameworks here. To get an idea how to run them look at:

https://github.com/inotify-tools/inotify-tools/blob/master/build_and_test.sh

Could you write a few tests please?

**Comment by tcf909** [comment]
@ericcurtin I'm not much of a C guy. Spent the morning trying to get a basic test written and was not able to succeed within the time I gave myself. The basics of C allude me (even with plenty of googling this AM).

My basic idea was just to append " %c" to any format strings ("Event %e %.e on %w %f %T %c") and then concat the expected result. Should be super simple, but I just can't figure it out. Result is a segfault at this point.

My code:
```
RESET;
    char cookie[12];
    sprintf(cookie, "%d", test_event->cookie);
    test_event->mask = IN_ACCESS;
    inotifytools_snprintf(buf, 1024, test_event, "Event %e %.e on %w %f %T %c");
    verify2(!strcmp(buf, strcat("Event ACCESS ACCESS on " TEST_DIR "/   ", cookie)), buf);
```

**Comment by tcf909** [comment]
This is certainly a needed feature to ensure more atomicity around move events (that are actually rename events) -- Move From -> Move To.

**Comment by ericcurtin** [comment]
No problem @tcf909 we have an integration test suite that is written in shell scripts if you'd prefer that avenue:

https://github.com/inotify-tools/inotify-tools/tree/master/t

Could you write a test in this form?

**Comment by tcf909** [comment]
much better option for me. will work on it this afternoon. thanks for the guidance.

**Comment by tcf909** [comment]
Ok. Test complete.

Testing for an initial create of a file (that doesn't have a cookie) followed by a move (mv) which has a cookie associated to it.

Should do the trick. 

Let me know if you want any changes made.

**Comment by ericcurtin** [comment]
Looks great I'll merge now and test myself also later just to be 110% sure. Thanks so much for the contribution

**Pull request merged**
