### PR TITLE
Fix printing of filename when watching a file (#157)

### PR DESCRIPTION
**Pull request by amir73il**

### CODE REVIEW

**Comment by ericcurtin** [comment]
@amir73il I'm guessing maybe:

```
char * c = csv_escape(inotifytools_event_to_str(event->mask);
c ? c : "";
```

will fix the FreeBSD build?

**Comment by amir73il** [comment]
ok Ill fix but do note that I did not change this line.

**Comment by ericcurtin** [comment]
I notice codecov started picking out the specific lines that aren't covered in this PR. Pretty nifty! Does this solve your problem @auouymous ?

**Comment by auouymous** [comment]
Yes, it 'fixes' the problem, thank you.

The man page needs to be updated to reflect the new behavior because `watched_filename` is now a `watched_dirname`, and `%w` is the `Watched directory`. It will of course break code and scripts that depend on the old behavior with full filename in the first column.

**Comment by auouymous** [comment]
Oops, spoke too soon. `inotifywait -q --csv foo` and `touch foo` outputs `,OPEN,`. The lack of a directory shows neither directory nor file. The new behavior of `dir EVENT file` might not work because a missing directory outputs nothing in the first column and makes it harder to parse (excluding CSV).

**Comment by amir73il** [comment]
@auouymous thanks for testing. It wasn't my intention to change behavior I simply did not read your report correctly.
So to be clear, the expectation is that is the case of a watched file, %w will be the path of the file and %f will be empty.
If I misunderstood again, please correct me. 
I will update the fix and the test accordingly.

**Comment by ericcurtin** [comment]
@auouymous would you like to write a test for this use case so your contribution can be committed to the t/ directory? It's a good way of ensuring the behaviour stays consistent.

**Comment by auouymous** [comment]
@amir73il That is correct, from the man page:

```
%w    This will be replaced with the name of the Watched file on which an event occurred.

%f    When an event occurs within a directory, this will be replaced with the name of the File
      which caused the event to occur. Otherwise, this will be replaced with an empty string.
```

But %w should probably be changed to `the watched file or directory`.

**Comment by auouymous** [comment]
It seems to work fine now, but what is output with fanotify when watching a file that has no directory path? Its behavior will need to be changed if it outputs nothing for %w because that makes it harder to parse. It would be fine if it automatically inserts `./` but the man page should mention that fanotify is not a drop-in replacement and document the new behavior for %w and %f when watching files.

**Comment by amir73il** [comment]
@auouymous there are nuance differences between inotify and fanotify.
fanotifywait is not indented to be a drop-in replacement for inotifywait, in the sense that is should produce the exact same output, only in the sense that it should provide the same knowledge (and more) about what transpired.
But you are right that the documentation should be updated to reflect that.

One difference is that fsnotifywait decodes the "watch path" from the event at the time the event is read, so even if the watched dir is renamed before you get the event, the printed path is uptodate. A by-product of this feature is that fsnotifywait always prints the full path of the watch, so in any case, parsers won't have any problem with an empty watch path.

Another subtle difference is that fanotify will not report two events for the same filesystem operation when watching both a directory and its child. As far as fanotify is concerned it is the same event and it self describes the target object regardless of the watch that caught it.

To illustrate the two differences above:
`
$ ./src/inotifywait -m -e open -q d d/x &
$ mv d c
$ echo > c/x
d/ OPEN x
d/x OPEN 
` 
`
$ sudo -E ./src/fsnotifywait -m -e open -q -r d d/x
$ mv d c
$ echo > c/x
/home/amir/src/inotify-tools/c/ OPEN x
`

**Comment by auouymous** [comment]
Okay, I wasn't sure if the inotifywait binary used fanotify when available and would thus change behavior. It should be fine to have separate documented behavior between the two binaries.

`man/inotifywait.1.in` also has `watched_filename` and `event_filename` that should mention fanotify behavior.

**Comment by ericcurtin** [comment]
We need a test for `--csv` option here

**Comment by ericcurtin** [comment]
Looking good, @auouymous what you think, does it solve the problem for you?

**Comment by ericcurtin** [comment]
And would you be happy to close #157 on completion of #158 or #159?

**Comment by auouymous** [comment]
@ericcurtin Yes, this closes #157. The behavior for inotifywait is the same as it was before 3.21.9.0.

**Pull request merged**
