### PR TITLE
Fix omission of --include/--includei options in man pages

### PR DESCRIPTION
**Pull request by kfollstad**
Hi - Thanks for working on this project, it has really helped me out in some tasks that I automate. In the course of writing some scripts, I noticed the --include/--includei options and accompanying descriptions were missing from the man pages for both inotifywait and inotifywatch. Hopefully including these will help someone else out there when they are using the tools for the first time.

### CODE REVIEW

**Comment by ericcurtin** [comment]
Hi @kfollstad,

Always delighted to hear this was useful! Thanks for spotting the gap in documentation and contributing, really appreciated. 
What you have written here makes sense, but I wonder should you just change "Do not process" from exclude/excludei to "Process" in include/includei to make it absolutely clear that these options are just opposites of each other like seen in the `print_help` function in #28 ?

```
.TP
.B \-\-exclude <pattern>
Do not process any events whose filename matches the specified POSIX extended
regular expression, case sensitive.

.TP
.B \-\-excludei <pattern>
Do not process any events whose filename matches the specified POSIX extended
regular expression, case insensitive.

.TP
.B \-\-include <pattern>
Process any events whose filename matches the specified POSIX extended
regular expression, case sensitive.

.TP
.B \-\-includei <pattern>
Process any events whose filename matches the specified POSIX extended
regular expression, case insensitive.
```

Ignore failed FreeBSD build, I have that fixed now.

**Comment by kfollstad** [comment]
Yes - I originally was thinking along those lines as well and had similarly just negated the --exclude man page section. However then I wondered if it was not clear or accurate enough. In the print_help function the language "Exclude all events on files except..." implies that there is a preexisting set of events that will be processed - i.e. those generated from the 'inotifywatch file1 [file2] [ ... ] and that --include or --exclude are just an additional filter that is applied.

If for instance
```
> touch test.txt test1.txt
> inotifywatch test.txt --include 'test1.txt' &
Establishing watches...
[1] 43022
> cat test1.txt
> fg 1
>^CNo events occured
```
Then "Process any events whose filename matches the specified POSIX extended regular expression" language would not strictly be true in this case. So I was trying to convey that events shown are given by the intersection of the files specified and the filter criteria. However maybe something like that would not be a confusion point in day to day usage and the language you gave will be more clear to someone who is (unlike me) not new to the tool and/or who is specifically looking to accomplish that filtering.

In any case, if you think that the "Process/Do not process" language is the way to go, I can resubmit that if that would be helpful.

**Comment by ericcurtin** [comment]
I understand, your terminology sounds good. I do question the "also match" terminology a little as it assumes that the user specified filenames, you could do a "-R ." for example and not specify filenames at all.

I think I'll be happy with what you write as long as it's consistent with the exclude options, which you are also free to edit if you think it could be written clearer!

**Comment by kfollstad** [comment]
I see what you are saying regarding the "also match" in conjunction with the "-r." That had not occurred to me. To try and rectify that, I took the language from the original --exclude(i) and tweaked it slightly & negated it for --include(i). I'm hoping it captures the sense of opposite-ness that you described, is more precise with regards to the "-r" flag, and describes the filtering that I was getting at. Thanks for taking a look!

**Comment by ericcurtin** [comment]
Merged, thanks again @kfollstad!

**Pull request merged**
