### PR TITLE
Extract stats into their own file

### PR DESCRIPTION
**Pull request by TorunR**
Hi,

we've extracted some parts concerning the file access event stats into their own file during the course of a scientific study. We want to check with whether this extraction seems sensible for you.

### CODE REVIEW

**Comment by ericcurtin** [comment]
I'll take a look later, only just very briefly looked at it. Is this only a refactoring? Any functional changes to point out?

**Comment by ericcurtin** [comment]
What is the scientific stuff also? I'm trying to learn a little more about what the varying users of this are using the tools for :smile:

**Comment by ericcurtin** [comment]
Thanks for making it easy to review, new unique lines:

```
++ b/libinotifytools/src/Makefile.am
libinotifytools_la_SOURCES = inotifytools.c inotifytools_p.h redblack.c redblack.h stats.c stats.h
++ b/libinotifytools/src/inotifytools.c
#include "stats.h"
int collect_stats = 0;
int init = 0;
void _niceassert( long cond, int line, char const * file,
++ b/libinotifytools/src/inotifytools_p.h
										  /**
* @internal
* Assert that a condition evaluates to true, and optionally output a message
* if the assertion fails.
*
* You should use the niceassert() preprocessor macro instead.
*
* @param  cond  If 0, assertion fails, otherwise assertion succeeds.
*
* @param  line  Line number of source code where assertion is made.
*
* @param  file  Name of source file where assertion is made.
*
* @param  condstr  Stringified assertion expression.
*
* @param  mesg  A human-readable error message shown if assertion fails.
*/
void _niceassert( long cond, int line, char const * file,
                  char const * condstr, char const * mesg );
extern int init;
extern struct rbtree *tree_wd;
++ b/libinotifytools/src/stats.c
#include "stats.h"
++ b/libinotifytools/src/stats.h
#ifndef STATS_H
#define STATS_H
#include "inotifytools.h"
#include "inotifytools/inotify.h"
#include "inotifytools_p.h"
extern int collect_stats;
void record_stats( struct inotify_event const * event );
unsigned int *stat_ptr(watch *w, int event);
watch *watch_from_wd(int wd);
#endif // STATS_H
```

**Comment by TorunR** [comment]
Hi,

thanks for accepting the Pullrequest. We don't use inotify directly, it rather is an evaluation target for an automated refactoring approach we are developing. We want to extract "modules" based on keyphrases, in this case "stats". 
I'd be curious about your opinion, whether an approach like this can be interesting.

**Comment by ericcurtin** [comment]
Could you show the code/script/designs? I guess it worked out ok here.

**Comment by NiLuJe** [comment]
This made libinotifytools' `_niceassert` symbol public (it was `static` before this), which breaks the build because the tools *also* define a public `_niceassert` symbol.

**Comment by ericcurtin** [comment]
Thanks so much for reporting @NiLuJe ! Two thinks needed here, I think. Add a statically linked build to our build script and remove the code duplication.

**Comment by ericcurtin** [comment]
Would you mind adding the exact way you build to:

build_and_test.sh

@NiLuJe 

and opening a PR?

**Pull request merged**
