### PR TITLE
feat(output): add --zero|-0 for NUL-separated events

### PR DESCRIPTION
**Pull request by DabeDotCom**
CSV mode trips up over filenames containing commas, and parsing output
containing newlines, quotes, and/or other special characters can lead
to any number of edge cases.

Separating event fields by `\0` NUL characters makes it significantly easier
and more robust for scripts to ingest the output of `inotifywait`, e.g.:

```
bash% inotifywait -0 -qmr /path/to/watch | perl -E '
  for (;;) {            # Loop
    local $/ = "\0";    # Same as "perl -0"
    chomp( my ( $dir, $event, $file ) = ( scalar <>, scalar <>, scalar <> ) );
    last unless $event;

    ### Do something with $dir, $event, and $file...
    say qq{DIR="$dir" -- EVENT="$event" -- FILE="$file"};
  }'

### CODE REVIEW

**Comment by ericcurtin** [comment]
Good idea, what would be even better is if you added a field separation option, kinda like awk:

```
       -F fs
       --field-separator fs
```

I'm sure some people won't like parsing nulls either and would like to introduce a new option after you to separate by a different value.

This PR has merge conflicts now.

**Comment by mikkorantalainen** [comment]
Another nice way to solve this would be to just add new formatting option. For example,

  --format "%e %w%f%x00"

that is, formatting code %xAB emits byte with hex value AB. Supporting any two digit hex value here would allow emitting any other bytes as the separator as required. This would be identical to git log formatting option. Maybe add some flag to avoid emitting the line feed after the output but  that is not really as important as the null byte because one can always run additional filtering to remove linefeed after the null byte if really needed.

**Comment by ericcurtin** [comment]
This was solved in #118 I believe, mind if I close this @DabeDotCom

**Comment by DabeDotCom** [comment]
> This was solved in #118 I believe, mind if I close this @DabeDotCom

As a great man once said: "There's More Than One Way To Do It."  «grin»

Thanks for taking up the charge!  :-D

PS — @mikkorantalainen, I like the flexibility of passing arbitrary hex chars (or unicode code points), but I'm guessing `%x00` won't work, since the `--format` string, quote, "*should be a format string suitable for passing to strftime(3)*", and `strftime(3)` already defines `%x` to mean "the locale's appropriate date representation" — e.g., `09/09/20` (or `09/09/20` if you're from the other side of the pond, hehe!)

**Comment by mikkorantalainen** [comment]
At least my copy of the documentation says that argument to `--timefmt` will be passed to `strftime()` but `--format` is just "using printf-like syntax" with a list supported conversions listing `%w`, `%f`, `%e`, `%Xe` and `%T` only. As such, `--format` could support syntax `%xAB` just fine.

And yes, I went through `strftime()` documentation too to see if I could emit zero byte via `%T`. Sadly, no.

**Pull request closed without merging**
