### PR TITLE
Add static builds to the CI script

### PR DESCRIPTION
**Pull request by NiLuJe**
Re #129

### CODE REVIEW

**Comment by ericcurtin** [comment]
Which way is the way you build it?

```
export CC=gcc
./autogen.sh
./configure --enable-static --disable-shared
make -j$j
```

Is it this way?

**Comment by NiLuJe** [comment]
Yep, with the failure now seen on all the CI bots ;).

**Comment by NiLuJe** [comment]
(The default is a mixed build: yes to both, which, in practice, means stuff gets linked against the shared library).

**Comment by ericcurtin** [comment]
The code now builds, but there are still tests to be fixed, see branch:

https://github.com/inotify-tools/inotify-tools/tree/test

**Comment by ericcurtin** [comment]
Thanks for the contribution and highlighting this! :smile:  I pushed it as part of b313b856c27f43f366e9a3f334d14b2b65f37ed1

Had to make some changes to the tests also, to keep them passing.

**Pull request closed without merging**
